tugas1_ppw/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import work_update_status.urls as work_update_status
import work_halaman_profile.urls as work_halaman_profile
import work_add_friend.urls as work_add_friend
import work_statistik.urls as work_statistik
from django.views.generic import RedirectView

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^update-status/', include(work_update_status,namespace='work_update_status')),
    url(r'^halaman-profile/', include(work_halaman_profile,namespace='work_halaman_profile')),
    url(r'^add-friend/', include(work_add_friend,namespace='work_add_friend')),
    url(r'^statistik/', include(work_statistik,namespace='work_statistik')),
    url(r'^$', RedirectView.as_view(url='/update-status/', permanent = 'true'), name='index')
]
    # Examples:
    # url(r'^$', 'tugas1_ppw.views.home', name='home'),
    # url(r'^tugas1_ppw/', include('tugas1_ppw.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

work_add_friend/urls.py
from django.conf.urls import url
from .views import index, friend_post
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^friendAdded', friend_post, name='addFriend'),
]

work_add_friend/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Friend(models.Model):
	name = models.CharField(max_length=27)
	URL = models.URLField()
	created_date = models.DateTimeField(auto_now_add=True)

work_add_friend/forms.py
from django import forms

class FriendURL_Form(forms.Form):
	error_messages = {
		'required': 'Tolong isi input ini',
		'invalid': 'Isi input dengan URL',
	}
	attrs = {
		'class': 'form-control'
	}

	name = forms.CharField(label='Nama', max_length=27, required = True, widget=forms.TextInput(attrs=attrs))
	URL = forms.URLField(widget=forms.URLInput(attrs=attrs), required = True)

work_add_friend/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .forms import FriendURL_Form
from .models import Friend
from django.http import HttpResponseRedirect

response = {}

# Create your views here.
def index (request):
    response['author'] = "Nabila Laili H"
    html = 'work_add_friend/work_add_friend.html'
    teman = Friend.objects.all()
    response['teman'] = teman
    response['friendurl_form'] = FriendURL_Form
    return render(request, html, response)

def friend_post(request):
	form = FriendURL_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
		response['URL'] = request.POST['URL'] if request.POST['URL'] != "" else "Anonymous"
		teman = Friend(name=response['name'], URL=response['URL'])
		teman.save()
		return HttpResponseRedirect('/add-friend/')
	else:
		return HttpResponseRedirect('/add-friend/')

work_add_friend/templates/work_add_friend/work_add_friend.html
{% extends "work_add_friend/layout/base.html" %}

{% block content %}

<!-- silakan diisi yeaks -->

<h1><b>Add Friend</b></h1>
<hr/>
<section name="form">
	<form id="form" method="POST" action="{% url 'work_add_friend:addFriend' %}">
		{% csrf_token %}
		{{ friendurl_form }}
		<br>
		<button type="Add Friend" class="btn btn-default">Add Friend</button>
	</form>
</section>
<table class="table">
	<h2>List Friend</h2>
	<thead>
		<th>Nama</th>
		<th>URL</th>
		<th>Dibuat Pada</th>
	</thead>
	<tbody>
	<!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
		{% for i in teman %}
		<tr>
			<td> {{i.name}} </td>
			<td><a href="{{i.URL}}"> {{i.URL}} </a></td>
			<td> {{i.created_date.time}} </td>
		</tr>
	{% endfor %}
	</tbody>
</table>


{% endblock %}