tugas1_ppw/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import work_update_status.urls as work_update_status
import work_halaman_profile.urls as work_halaman_profile
import work_add_friend.urls as work_add_friend
import work_statistik.urls as work_statistik
from django.views.generic import RedirectView

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^update-status/', include(work_update_status,namespace='work_update_status')),
    url(r'^halaman-profile/', include(work_halaman_profile,namespace='work_halaman_profile')),
    url(r'^add-friend/', include(work_add_friend,namespace='work_add_friend')),
    url(r'^statistik/', include(work_statistik,namespace='work_statistik')),
    url(r'^$', RedirectView.as_view(url='/update-status/', permanent = 'true'), name='index')
]
    # Examples:
    # url(r'^$', 'tugas1_ppw.views.home', name='home'),
    # url(r'^tugas1_ppw/', include('tugas1_ppw.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

work_halaman_profile/urls.py
from django.conf.urls import url
from .views import index
# url for app
urlpatterns = [
     url(r'^$', index, name='index'),
]

work_halaman_profile/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Profile(models.Model):
    name = models.CharField(max_length = 100, unique = True)
    birthday = models.DateField()
    gender = models.CharField(max_length = 10)
    expertise = models.CharField(max_length = 100)
    description = models.TextField()
    email = models.EmailField()
    image = models.TextField(default="https://i.pinimg.com/736x/f1/03/c3/f103c3c8b80e7a8cc77958c0811f8853--team-unicorn-unicorns-art-drawing.jpg")

work_halaman_profile/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import Profile

response = {}
#bio_dict = [{'subject' : 'Birthday', 'value' : '01 Jan'},\
#{'subject' : 'Gender', 'value' : 'Female'},\
#{'subject' : 'Expertise', 'value' : 'Marketing'},\
#{'subject' : 'Description', 'value' : 'lalala'},\
#{'subject' : 'Email', 'value' : 'lalaa@gmail.com'}]

# Create your views here.
def index (request):
    # response = {'bio_dict':bio_dict}
    if Profile.objects.all().count() == 0:
        Profile.objects.create(name='Ubiquitous', birthday='2017-10-07', gender='Male', expertise='Living life', description='Live life to the fullest', email='ubiquitous@life.com', image='https://i.pinimg.com/736x/f1/03/c3/f103c3c8b80e7a8cc77958c0811f8853--team-unicorn-unicorns-art-drawing.jpg')

    profile = Profile.objects.get(name = 'Ubiquitous')
    response['author'] = "M. Ikhsan Kurniawan"
    response['profile'] = profile
    html = 'work_halaman_profile/work_halaman_profile.html'
    return render(request, html, response)

work_halaman_profile/templates/work_halaman_profile/partials/footer.html
<!-- templates/work_halaman_profile/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<style>
p{
  margin: center;
  text-align: center;
  font-family: "Proxima Nova";
  color: grey;
}
</style>
<p>© Made with Love by {{author}}</p>

work_halaman_profile/templates/work_halaman_profile/partials/header.html
<!-- tugas_1/templates/work_halaman_profile/partials/header.html-->
<!-- navbar template for all apps-->


<style>
.navbar-nav{
  width: 90%;
}
ul{
  list-style-type:none;
  display:flex;
  justify-content: center;

}
ul li{
  display: list-item;
  background: transparent;
  padding: 1px 10px;
  color:white;
  margin: 0 3px;
  font-family: "Proxima Nova";
}

</style>

<nav class = "navbar navbar-center navbar-inverse navbar-static-top">
  <div class = "container-fluid">
    <div class = "navbar-header">
      <button type = "button" class = "navbar-toggle collapsed" data-toggle = "collapse" data-target="#navbar" aria-expanded = "false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand logo-utama-lingin" href="{% url 'work_halaman_profile:index' %}">lingin</a>
    </div>
    <div class="collapse navbar-collapse"id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'work_update_status:index' %}">Status</a></li>
        <li><a href="{% url 'work_halaman_profile:index' %}">Profile</a></li>
        <li><a href="{% url 'work_add_friend:index' %}">Friends</a></li>
        <li><a href="{% url 'work_statistik:index' %}">Statistik</a></li>
      </ul>
    </div>
  </div>
</nav>